"""19-08-plant

Revision ID: 5c8a63316354
Revises: 2264118e9331
Create Date: 2023-08-19 20:39:39.593552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8a63316354'
down_revision: Union[str, None] = '2264118e9331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('flower', 'shrub', 'tree', name='planttype'), nullable=True),
    sa.Column('classification', sa.Enum('common', 'rare', 'epic', name='plantclass'), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('growth_stage', sa.Integer(), nullable=True),
    sa.CheckConstraint('growth_stage >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plant_id')
    )
    op.add_column('garden', sa.Column('plant_id', sa.Integer(), nullable=True))
    op.add_column('garden', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_unique_constraint(None, 'garden', ['plant_id'])
    op.create_foreign_key(None, 'garden', 'plant', ['plant_id'], ['id'])
    op.drop_column('garden', 'size')
    op.add_column('user', sa.Column('wallet', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wallet')
    op.add_column('garden', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'garden', type_='foreignkey')
    op.drop_constraint(None, 'garden', type_='unique')
    op.drop_column('garden', 'price')
    op.drop_column('garden', 'plant_id')
    op.drop_table('user_plant')
    op.drop_table('plant')
    # ### end Alembic commands ###
